Create serializers, viewsets, attach to routers
jeevansurendran/boots pull request #1
Opened 2020-12-22 16:36 UTC by Electromorphous

2020-12-22 17:39 UTC, jeevansurendran requested changes

2020-12-22 17:39 UTC, jeevansurendran commented on src/api/models.py
> +# youtu.be/dQw4w9WgXcQ
I got rick rolled 🤣🤣🤣, can we remove these lines now

2020-12-22 17:39 UTC, jeevansurendran commented on src/api/viewsets.py
> +# youtu.be/dQw4w9WgXcQ
Here too

2020-12-23 04:09 UTC, Electromorphous commented on src/api/viewsets.py
> +# youtu.be/dQw4w9WgXcQ
Okay 😂

2020-12-23 05:38 UTC, merged